### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mgolant** [GioF71/upmpdcli-docker#431]
hi 
I use moode 9.05 
your tidal-connect docker works fine, but upmdcli-docker configured to play HIRES, is connected but gets an error when starting to play 
I'm able to browse my playlists but not able to play anything 
the error: Device sent an error response

**Comment by GioF71** [comment]
Hello, can you post your docker-compose file, and the container logs?
I assume you are playing against moode itself, it that correct?
Thank you

**Comment by mgolant** [comment]
[tidal-hires_docker_logs.log](https://github.com/user-attachments/files/16412147/tidal-hires_docker_logs.log)
I assume you are playing against moode itself, it that correct? - yes 
mconnect -> browser -> Tidal Hires ( upmpdcli ) -> Tidal 
 Tidal Hires ( upmpdcli )  means docker

**Comment by GioF71** [comment]
is [this](https://listen.tidal.com/album/7239776) the album you are trying to play?

**Comment by mgolant** [comment]
looks like I'm able to stream music to my moode device after enabling Moode UPNP client and choosing Moode UPNP in UPnP devices but only regular FLAC - not hires

**Comment by mgolant** [comment]
I finally figured it out. :) But why do I need to enable Moode UPNP itself? The UPNP service from the Docker was used.
[tidal-hires_docker_logs_new.log](https://github.com/user-attachments/files/16412887/tidal-hires_docker_logs_new.log)

**Comment by GioF71** [comment]
It seems you are getting some errors for tracks/albums not available. From the logs it seems you are in Nigeria, your profile says Israel. Are you using a VPN?
I am playing the same album without issue.
Anyway, maybe try with oauth2 authentication mode first. You might have to rename your existing pkce.credentials.json to a different name in order to fall back to the simpler oauth2 mode. If you are using [this](https://github.com/GioF71/audio-tools/tree/main/media-servers/tidal-hires) example, you can try to run get-oauth2-credentials.sh to generate a credentials.json file.
Also set TIDAL_AUDIO_QUALITY=HI_RES for this test.

**Comment by mgolant** [comment]
No VPN, but I use an account that was opened in Nigeria :)

**Comment by GioF71** [comment]
So I understand you have probably enabled the renderer in the upmpdcli container. That's not strictly needed when using Moode because Moode already has support for a UPnP renderer. In order to enable it, go to Configure -> Settings -> Renderers -> enable "UPnP Client for MPD"

**Comment by GioF71** [comment]
> No VPN, but I use an account that was opened in Nigeria :)

ok, I don't know if this can be an issue with specific albums, and I can't reproduce this :-)
But I will see if the preferred country can be set somehow.

**Comment by mgolant** [comment]
> So I understand you have probably enabled the renderer in the upmpdcli container. That's not strictly needed when using Moode because Moode already has support for a UPnP renderer. In order to enable it, go to Configure -> Settings -> Renderers -> enable "UPnP Client for MPD"
> 
> Edit: looks like you did not enable the media server to also be a renderer from the logs. Unless you were running another upmpdcli container for that purpose

I'm already confused :) I assumed that when running the docker, the renderer should start automatically ( not moode renderer - the renderer that docker has )
but no ...
my steps :
1 . docker pull giof71/upmpdcli
2.  git clone https://github.com/GioF71/audio-tools.git
3. cd ~/audio-tools/media-servers/tidal-hires
4. ./get-pkce-credentials.sh
5. docker-compose up -d
6 . edit .env to enable HIRES ( TIDAL_AUDIO_QUALITY=HI_RES_LOSSLESS  + TIDAL_DOWNLOAD_PLUGIN=yes )
7. docker-compose restart

and no UPnP devices till enabling moode UPnP itself 
what wrong ?

**Comment by GioF71** [comment]
Yes, that configuration is for a media server only. It does not create a renderer. Nothing is wrong with your configuration. 
The idea is that the media server can run on any headless server, possibly without audio capabilities, so, by default, I was not considering enabling the renderer on that container.
I understand that in your case, if you want to run the media server on the same pi which runs moode, you might want to make it works as a renderer also, so you don't need to enable UPnP renderer on moode.
This is not currently supported in that example, but I might add support and documentation for this use-case as soon as I can.

**Comment by mgolant** [comment]
> Yes, that configuration is for a media server only. It does not create a renderer. Nothing is wrong with your configuration. The idea is that the media server can run on any headless server, possibly without audio capabilities, so, by default, I was not considering enabling the renderer on that container. I understand that in your case, if you want to run the media server on the same pi which runs moode, you might want to make it work as a renderer also, so you don't need to enable UPnP renderer on moode. This is not currently supported in that example, but I might add support and documentation for this use-case as soon as I can.

It would be nice! :) Thank you for your support !!!

**Comment by GioF71** [comment]
Also, consider that just enabling the renderer wouldn't necessarily guarantee that you get a working renderer. In your case it would, because you are running Moode, which incorporates Music Player Daemon.
Should I add support for enabling the renderer, the MPD would become a pre-requisite.
In other words, if one wants to run the media server on Moode, you can just enable moode's UPnP renderer and you are good to go.
If one wants to run the media server on a bare os, but also want the renderer to run on the same device, he can use [this other stack](https://github.com/GioF71/audio-tools/tree/main/players/upnp-renderer/upnp-renderer-user-mode) in order to get a mpd+upmpdcli running as the renderer

**Comment by mgolant** [comment]
Anyway, thanks a lot!
But it would be nice if this was described in the documentation :)

**Comment by GioF71** [comment]
I will do that as soons as I can. The most important thing for now is to state on the media server that the configuration does not create a renderer and maybe redirect the user to a sample configuration.

Please star the repositories if you can, this is always encouraging!

**Comment by GioF71** [comment]
Hello, please have a look again [here](https://github.com/GioF71/audio-tools/tree/main/media-servers/tidal-hires) for the changes we discussed. Feedback is appreciated!
